---
title: "Paquetes en R 游닍"
subtitle: "Agregando nuevas funcionalidades el lenguaje"
date: "last-modified"
lang: "es"
toc: true
code-line-numbers: true
code-copy: true
format: html
bibliography: references.bib
---

<link rel="stylesheet" href="https://unpkg.com/keyboard-css@1.2.2/dist/css/main.min.css" />


## Historia r치pida de R y Rstudio

R es un lenguaje de programaci칩n y entorno de software libre para an치lisis estad칤stico y gr치fico. Fue creado en 1993 por Ross Ihaka y Robert Gentleman en la Universidad de Auckland, Nueva Zelanda, como una implementaci칩n de c칩digo abierto del lenguaje S desarrollado por John Chambers en los Laboratorios Bell [@Ihaka1996].

En 2000, se lanz칩 la versi칩n 1.0 de R [@RCoreTeam2008]. Desde entonces, ha ganado popularidad en la comunidad estad칤stica y de ciencia de datos debido a su flexibilidad y capacidad para crear gr치ficos de alta calidad.

RStudio, por otro lado, es un entorno de desarrollo integrado (IDE) para R. Fue fundado por JJ Allaire en 2009, con la primera versi칩n beta p칰blica lanzada en febrero de 2011 [@Allaire2011]. RStudio facilita el uso de R al proporcionar una interfaz gr치fica amigable, herramientas de depuraci칩n, visualizaci칩n de datos y gesti칩n de proyectos.

En los 칰ltimos a침os, el enfoque de R se ha desplazado hacia la accesibilidad para no programadores, principalmente a trav칠s del ecosistema tidyverse. Tidyverse, introducido por Hadley Wickham en 2016, es una colecci칩n de paquetes de R dise침ados para ciencia de datos que comparten una filosof칤a de dise침o com칰n [@Wickham2019].

Este enfoque ha simplificado significativamente el an치lisis de datos para usuarios sin experiencia en programaci칩n, permiti칠ndoles realizar an치lisis complejos con c칩digo m치s intuitivo y legible.

Para comprender mejor la filosof칤a detr치s de tidyverse, se recomienda encarecidamente la lectura del "[Tidyverse design guide](https://tidyverse.tidyverse.org/articles/manifesto.html)" [@Wickham2019Guide].
Este documento explica detalladamente los principios y la visi칩n que gu칤an el desarrollo de tidyverse, ofreciendo una comprensi칩n m치s profunda de c칩mo este ecosistema est치 dise침ado para hacer que el an치lisis de datos sea m치s accesible y eficiente.
